# Generated by Django 5.1.4 on 2024-12-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hakodaterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakodaterestaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
