# Generated by Django 5.1.4 on 2024-12-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hakodaterestaurant_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakodaterestaurant',
            name='logo_image',
            field=models.URLField(default='https://imgfp.hotp.jp/IMGH/70/08/P033307008/P033307008_69.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hakodaterestaurant',
            name='url_pc',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
