# Generated by Django 5.1.4 on 2024-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hakodaterestaurant_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakodaterestaurant',
            name='pickup_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hakodaterestaurant',
            name='logo_image',
            field=models.URLField(default='https://imgfp.hotp.jp/IMGH/70/08/P033307008/P033307008_69.jpg'),
        ),
        migrations.AlterField(
            model_name='hakodaterestaurant',
            name='url_pc',
            field=models.URLField(default='https://example.com'),
        ),
    ]
